---
SEEDS: [32,64,128,256]

#Execution
TRAIN: True 
TEST: False 
PREDICT_NORMAL: True
DEVICE: "cuda"

# Directories
TRAIN_DIR: './data/train'
# TRAIN_DIR: './mini_data/train'
TEST_DIR: './mini_data/test'
WEIGHTS_DIR: './models/weights'
CHKPTS_DIR : './models/checkpoints'
OUTPUT_DIR: './data/outputs'
ENCODE_DIR: './data/encodings'

# Data Details
IMSIZE: 256
CATEGORY: 'Airplane'
# SKETCH_VIEWS: ['F','S','T']
SKETCH_VIEWS: ['F','S']
SKETCH_VARIATIONS: 4
NUM_DN_VIEWS: 12
# NUM_DN_VIEWS: 6
NUM_DNFS_VIEWS: 2
NORM_MEAN : [0.5,0.5,0.5]
NORM_STD : [0.5,0.5,0.5]

# Training Details
BATCH_SIZE: 2
EPOCHS: 100
LR: 0.0001
NUM_BATCH_CHKPTS: 5

