---
SEEDS: [32,64,128,256]

#Execution
TRAIN: False 
TEST: False 

# Directories
TRAIN_DIR: './data/train'
TEST_DIR: './data/test'
WEIGHTS_DIR: './models/weights'
CHKPTS_DIR : './models/checkpoints'
OUTPUT_DIR: './data/outputs'
ENCODE_DIR: './data/encodings'

# Data Details
IMSIZE: 256
CATEGORY: 'Character'
SKETCH_VIEWS: ['F','S','T']
SKETCH_VARIATIONS: 4
NUM_DN_VIEWS: 12
NORM_MEAN : [0.485,0.456,0.406]
NORM_STD : [0.229,0.224,0.225]

# Training Details
BATCH_SIZE: 2
EPOCHS: 500
LR: 1e-4

